FROM amazoncorretto:17-alpine-jdk
LABEL maintainer="daido7031@gmail.com"
COPY target/demo-java-spring-boot-0.0.1-SNAPSHOT.jar demo-java-spring-boot-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","demo-java-spring-boot-0.0.1-SNAPSHOT.jar"]